argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - test-argocd.example.com
      paths:
        - /
      pathType: Prefix
      tls:
        - secretName: test-argocd
          hosts:
            - test-argocd.example.com
    repositories: 
      apps-argocd:
        url: https://github.com/giddy87/container-excercises
        name: container-excercises




      
