apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-source
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
  steps:
  - name: list-source
    image: ubuntu
    workingDir: $(workspaces.source.path)
    script: >
      ls
