apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-push-hds
  namespace: tekton-runs
spec:
  params:
  - name: repo-url
    value: git@github.com:giddy87/Budget-App.git
  - name: image-reference
    value: giddy87/rubyapp
  - name: image-tag
    value: 3.0.1
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credential
  serviceAccountName: git-service-account
